-- Add more restaurants to reach 100+ total in LA and Irvine

INSERT INTO restaurants (name, cuisine_slug, neighborhood, region, address, hours, price_range) VALUES
('Gogi House', 'korean', 'Koreatown', 'Los Angeles', '3870 W Olympic Blvd, LA', '11am-11pm', '$$'),
('Dae Jang Kum', 'korean', 'Koreatown', 'Los Angeles', '3470 W 8th St, LA', '11am-11pm', '$$'),
('Soot Bul House', 'korean', 'Koreatown', 'Los Angeles', '3625 W 8th St, LA', '10:30am-11pm', '$$'),
('Tsujita', 'japanese', 'Little Tokyo', 'Los Angeles', '2050 Sawtelle Blvd, LA', '11am-10pm', '$$'),
('Katsu-Ya', 'japanese', 'Studio City', 'Los Angeles', '11680 Ventura Blvd, LA', '11:30am-10:30pm', '$$'),
('Hamasaku', 'japanese', 'Downtown LA', 'Los Angeles', '127 Japanese Village Plaza, LA', '11am-10pm', '$$'),
('Enoki', 'japanese', 'Silver Lake', 'Los Angeles', '3904 Sunset Blvd, LA', '5pm-11pm', '$$$'),
('Rhong Tiam', 'thai', 'Silver Lake', 'Los Angeles', '4019 Sunset Blvd, LA', '11am-10pm', '$$'),
('Pestobar Soi 38', 'thai', 'Los Feliz', 'Los Angeles', '4700 Los Feliz Blvd, LA', '11am-10pm', '$$'),
('Pho Kim Long', 'vietnamese', 'Chinatown', 'Los Angeles', '970 N Hill St, LA', '9am-9pm', '$'),
('Banh Mi My Tho', 'vietnamese', 'Boyle Heights', 'Los Angeles', '4514 Whittier Blvd, LA', '10am-6pm', '$'),
('Thanh Huong', 'vietnamese', 'Midtown', 'Los Angeles', '5012 Hollywood Blvd, LA', '10am-9:30pm', '$'),
('Chengdu Taste', 'chinese', 'San Gabriel', 'Los Angeles', '408 S Garfield Ave, San Gabriel', '11am-10pm', '$$'),
('China Palace', 'chinese', 'Chinatown', 'Los Angeles', '988 N Broadway, LA', '11am-10:30pm', '$$'),
('Rickys Fish Tacos', 'mexican', 'Santa Monica', 'Los Angeles', '1514 Ocean Park Blvd, LA', '11am-10pm', '$$'),
('Mas Malo', 'mexican', 'Silver Lake', 'Los Angeles', '3900 Sunset Blvd, LA', '5pm-11pm', '$$'),
('Casa Vega', 'mexican', 'Studio City', 'Los Angeles', '11928 Ventura Blvd, LA', '11am-11pm', '$$'),
('Bestia', 'italian', 'Arts District', 'Los Angeles', '2121 E 7th Pl, LA', '5pm-11pm', '$$'),
('Republique', 'italian', 'West Hollywood', 'Los Angeles', '8512 Melrose Ave, LA', '8am-10pm', '$$'),
('A Voce', 'italian', 'Downtown LA', 'Los Angeles', '525 W 7th St, LA', '11:30am-2:30pm, 5:30pm-11pm', '$$$'),
('Naan Kabob', 'indian', 'West LA', 'Los Angeles', '11920 Wilshire Blvd, LA', '11:30am-10pm', '$$'),
('Indigo', 'indian', 'Santa Monica', 'Los Angeles', '1456 Ocean Park Blvd, LA', '5pm-10pm', '$$$'),
('Gwen', 'american', 'Downtown LA', 'Los Angeles', '600 W 7th St, LA', '5pm-10pm', '$$$'),
('Sycamore Kitchen', 'american', 'Arts District', 'Los Angeles', '2016 E 7th Pl, LA', '5pm-11pm', '$$'),
('Three Weld', 'american', 'Arts District', 'Los Angeles', '2015 E 7th Pl, LA', '5pm-11pm', '$$'),
('Republique Med', 'mediterranean', 'West Hollywood', 'Los Angeles', '8512 Melrose Ave, LA', '8am-10pm', '$$'),
('Avra', 'mediterranean', 'Beverly Hills', 'Los Angeles', '9360 Wilshire Blvd, Beverly Hills', '11:30am-11pm', '$$$'),
('Comme Ca', 'french', 'West Hollywood', 'Los Angeles', '8001 Sunset Blvd, LA', '5pm-11pm', '$$$'),
('Petit Trois', 'french', 'Downtown LA', 'Los Angeles', '718 N Spring St, LA', '11am-3pm, 5pm-10:30pm', '$$'),
('Gamys', 'filipino', 'Downtown LA', 'Los Angeles', '923 N Main St, LA', '10am-10pm', '$'),
('Patricios', 'filipino', 'Los Angeles', '5200 Hollywood Blvd, LA', '11am-10pm', '$$'),
('Gen Korean BBQ House', 'korean', 'Irvine Spectrum', 'Irvine', '72 Peach Tree Ln, Irvine', '11am-11pm', '$$'),
('Seoul Sausage Company', 'korean', 'Irvine', 'Irvine', '2850 Kelvin Ave, Irvine', '10am-10pm', '$$'),
('Santouka Ramen', 'japanese', 'Irvine Spectrum', 'Irvine', '1 Spectrum Pointe, Irvine', '11am-10pm', '$$'),
('Kotobuki', 'japanese', 'Irvine', 'Irvine', '17842 Von Karman Ave, Irvine', '11am-10pm', '$$'),
('Pad Thai King', 'thai', 'Irvine', 'Irvine', '2830 Kelvin Ave, Irvine', '11am-10pm', '$$'),
('Thai Ginger', 'thai', 'Irvine Spectrum', 'Irvine', '1 Spectrum Pointe, Irvine', '11am-10pm', '$$'),
('Pho Hoa Noodle Soup', 'vietnamese', 'Irvine', 'Irvine', '17850 Von Karman Ave, Irvine', '10:30am-9pm', '$'),
('Saigon Kitchen', 'vietnamese', 'Irvine', 'Irvine', '2810 Kelvin Ave, Irvine', '11am-9:30pm', '$$'),
('Keke Shanghai', 'chinese', 'Irvine', 'Irvine', '17840 Von Karman Ave, Irvine', '11am-9pm', '$$'),
('Taiwan Cafe', 'chinese', 'Irvine', 'Irvine', '2845 Kelvin Ave, Irvine', '11am-9pm', '$'),
('Qdoba Mexican Grill', 'mexican', 'Irvine', 'Irvine', '1 Spectrum Pointe, Irvine', '10:30am-10pm', '$$'),
('Casa de Tacos', 'mexican', 'Irvine', 'Irvine', '2820 Kelvin Ave, Irvine', '11am-10pm', '$$'),
('Bacco Ristorante', 'italian', 'Irvine', 'Irvine', '17900 Von Karman Ave, Irvine', '11:30am-10pm', '$$'),
('Marcellos', 'italian', 'Irvine', 'Irvine', '17851 Von Karman Ave, Irvine', '11:30am-10pm', '$$'),
('Curry in a Hurry', 'indian', 'Irvine', 'Irvine', '2815 Kelvin Ave, Irvine', '11am-10pm', '$$'),
('India Palace', 'indian', 'Irvine Spectrum', 'Irvine', '1 Spectrum Pointe, Irvine', '11am-10pm', '$$'),
('Dave and Busters', 'american', 'Irvine Spectrum', 'Irvine', '1 Spectrum Pointe, Irvine', '11am-midnight', '$$'),
('Claim Jumper', 'american', 'Irvine', 'Irvine', '17881 Von Karman Ave, Irvine', '11am-10pm', '$$'),
('Olive Garden', 'mediterranean', 'Irvine Spectrum', 'Irvine', '1 Spectrum Pointe, Irvine', '11am-10pm', '$$'),
('Kabuki Restaurant', 'mediterranean', 'Irvine', 'Irvine', '17860 Von Karman Ave, Irvine', '11am-10pm', '$$'),
('Le Bernardin', 'french', 'Irvine', 'Irvine', '17880 Von Karman Ave, Irvine', '11:30am-10pm', '$$$'),
('Jollibee', 'filipino', 'Irvine Spectrum', 'Irvine', '1 Spectrum Pointe, Irvine', '10:30am-10pm', '$'),
('Goldilocks Bakery', 'filipino', 'Irvine', 'Irvine', '2835 Kelvin Ave, Irvine', '10am-8pm', '$')
ON CONFLICT DO NOTHING;
